export const contractTypeToFields = {
    "c-ev-pp": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfrist",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung"
    ],
    "eng-ev-pp": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfrist",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung",
        "addAgreements"
    ],
    "proj-ev-pp": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfrist",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung",
        "addAgreements"
    ],
    "c-ev-pp-eng": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfristEnglisch",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung",
        "addAgreements"
    ],
    "eng-ev-pp-eng": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfristEnglisch",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung",
        "addAgreements"
    ],
    "proj-ev-pp-eng": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "wematchAnsprechpartnerName",
        "ppGesellschaft",
        "projektpartnerName",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfristEnglisch",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "einsatzort",
        "position",
        "aufgabenbeschreibung",
        "addAgreements"
    ],
    "c-rv-kunde": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity"
    ],
    "c-ev-kunde": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "wematchAnsprechpartnerName",
        "ansprechpartnerKunde",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfrist",
        "einsatzort",
        "position",
        "aufgabenbeschreibung"
    ],
    "c-ev-kunde-eng": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "kunde",
        "adresseKundeStr",
        "adresseKundeCity",
        "wematchAnsprechpartnerName",
        "ansprechpartnerKunde",
        "matchID",
        "tagessatz",
        "stundensatz",
        "festpreis",
        "startdatum",
        "enddatum",
        "kuendigungsfristEng",
        "einsatzort",
        "position",
        "aufgabenbeschreibung"
    ],
    "c-rv": [
        "absenderName",
        "absenderMail",
        "empfaengerName",
        "empfaengerMail",
        "ccName",
        "ccMail",
        "ppStreet",
        "ppCity",
    ],
};

const baseDocxFields = [
    "matchID",
    "wematchAnsprechpartnerName",
    "startdatum",
    "enddatum",
    "adresseKundeStr",
    "adresseKundeCity",
    "kunde",
    "kuendigungsfrist",
    "einsatzort",
    "position",
    "ansprechpartnerKunde",
    "tagessatz",
    "stundensatz",
    "festpreis",
    "auslastung",
    "auslastungEng",
    "aufgabenbeschreibung",
]

const defaultDocxFields = [
    "addAgreements",
    "ppStreet",
    "ppCity",
    "projektpartnerName",
    "projectHours",
    "remotePercentage",
    "daysPerWeek",
    "ppGesellschaft",
    "preFix",
]

export const docxTypeToFields = {
    "contract": baseDocxFields.concat(defaultDocxFields,
        "kuendigungsfirstEnglisch"),
    "termination":
        baseDocxFields.concat(defaultDocxFields,
            "selectedPerson"),
    "offer": baseDocxFields.concat([
        "projectHours",
        "gesamtPreis",
        "selectedPerson",
        "zahlungszielKunde",
        "stundensatzOnSite",
        "stundensatzRemote",
        "projectDays",
        "auslastung",
        "tagessatzOnSite",
        "tagessatzRemote",
        "prefixKunde"]),
};

export const fieldNameToDocusignParameterName = {
    "absenderName": "Absender_UserName",
    "absenderMail": "Absender_Email",
    "empfaengerName": "Kunde_UserName",
    "empfaengerMail": "Kunde_Email",
    "empfaengerName2": "Kunde2_UserName",
    "empfaengerMail2": "Kunde2_Email",
    "ccName": "CC_UserName",
    "ccMail": "CC_Email",
    "kunde": "Kunde",
    "adresseKundeStr": "KundeAdresse1",
    "adresseKundeCity": "KundeAdresse2",
    "wematchAnsprechpartnerName": "Wematch_Ansprechpartner",
    "ansprechpartnerKunde": "Ansprechpartner_Kunde",
    "matchID": "MatchID",
    "tagessatz": "Tagessatz",
    "stundensatz": "Stundensatz",
    "festpreis": "Festpreis",
    "startdatum": "Startdatum",
    "enddatum": "Enddatum",
    "kuendigungsfrist": "Kuendigungsfrist",
    "ppNameLocal": "PPName",
    '"Nach Abschätzung"': "Auslastung",
    "einsatzort": "Einsatzort",
    "position": "Position",
    "aufgabenbeschreibung": "Aufgabenbeschreibung",
    "ppGesellschaft": "PP_Gesellschaft",
};

export const helpMailFields = [
    "permission",
    "absenderName",
    "absenderMail",
    "empfaengerName",
    "empfaengerMail",
    "ccName",
    "ccMail",
    "wematchAnsprechpartnerName",
    "ppGesellschaft",
    "projektpartnerName",
    "matchID",
    "tagessatz",
    "stundensatz",
    "festpreis",
    "startdatum",
    "enddatum",
    "kuendigungsfrist",
    "kunde",
    "adresseKundeStr",
    "adresseKundeCity",
    "einsatzort",
    "position",
    "aufgabenbeschreibung"
]